apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqld-exporter-config
  namespace: your-namespace
data:
  config.yaml: |
    ---
    datasources:
      - name: your-datasource-name
        type: mysql
        host: your-mysql-host
        port: your-mysql-port
        username: your-mysql-username
        password: your-mysql-password
        timeout: 5s
        tls:
          enabled: false
    metrics:
      - name: mysql_status
        query: SHOW GLOBAL STATUS
      - name: mysql_variables
        query: SHOW GLOBAL VARIABLES
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqld-exporter
  namespace: your-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqld-exporter
  template:
    metadata:
      labels:
        app: mysqld-exporter
    spec:
      containers:
        - name: mysqld-exporter
          image: prom/mysqld-exporter:v0.14.0
          ports:
            - containerPort: 9104
          args:
            - "--config.my-cnf=/etc/config/config.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: mysqld-exporter-config
